basePath: /api
definitions:
  model.Current:
    properties:
      temp_c:
        type: number
    type: object
  model.Location:
    properties:
      country:
        type: string
      name:
        type: string
    type: object
  model.Weather:
    properties:
      current:
        $ref: '#/definitions/model.Current'
      location:
        $ref: '#/definitions/model.Location'
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Another one weather api.
  license:
    name: MIT
    url: https://github.com/cortezzIP/Weather-API/blob/main/LICENSE
  title: Weather API
  version: "1.0"
paths:
  /weather/current:
    get:
      consumes:
      - application/json
      description: Get current weather by location
      parameters:
      - description: Location
        in: query
        name: location
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Weather'
        "400":
          description: error
          schema:
            type: string
      summary: Get current weather
      tags:
      - weather
swagger: "2.0"
